/**
 * POST /api/participants/reset-password
 *
 * Admin-initiated password reset: sets a new password on the Supabase Auth user.
 * The new password is generated by the client (shown once in modal, NOT stored).
 *
 * Auth: admin only
 */

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createClient as createSupabaseAdmin } from "@supabase/supabase-js";
import { getAuthenticatedUser, isAdmin } from "@/lib/api-auth";
import { createClient } from "@/lib/supabase/server";

// ---------------------------------------------------------------------------
// Input schema
// ---------------------------------------------------------------------------

const resetPasswordSchema = z.object({
  userId: z.string().uuid("userId must be a valid UUID"),
  workEmail: z.string().email("Invalid email"),
  newPassword: z.string().min(8).max(128),
});

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------

export async function POST(request: NextRequest) {
  const user = await getAuthenticatedUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (!isAdmin(user)) {
    return NextResponse.json({ error: "Forbidden: admin only" }, { status: 403 });
  }

  let rawBody: unknown;
  try {
    rawBody = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = resetPasswordSchema.safeParse(rawBody);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Validation error", details: parsed.error.issues },
      { status: 400 },
    );
  }

  const { userId, workEmail, newPassword } = parsed.data;

  const supabase = await createClient();

  // Resolve the Supabase Auth UUID from the users table
  const { data: profile, error: profileError } = await supabase
    .from("users")
    .select("id, auth_id")
    .eq("id", userId)
    .eq("work_email", workEmail)
    .single();

  if (profileError || !profile) {
    return NextResponse.json({ error: "User not found" }, { status: 404 });
  }

  const adminClient = createSupabaseAdmin(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  );

  const { error: authError } = await adminClient.auth.admin.updateUserById(
    profile.auth_id,
    { password: newPassword },
  );

  if (authError) {
    return NextResponse.json(
      { error: "Failed to reset password", details: authError.message },
      { status: 500 },
    );
  }

  // Audit log (non-critical)
  await supabase.from("audit_log").insert({
    entity_type: "users",
    entity_id: userId,
    action: "update" as const,
    new_value: { action: "password_reset", performed_by: user.userId },
    performed_by: user.userId,
  });

  return NextResponse.json({ success: true });
}
